<?php

/**
 * @file
 * Contains feedbackify.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function feedbackify_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the feedbackify module.
    case 'help.page.feedbackify':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrates the Feedbackify service') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function feedbackify_theme() {
  $theme = [];

  return $theme;
}
